//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
[System.Xml.Serialization.XmlRootAttribute("order", Namespace="http://walmart.com/mp/orders", IsNullable=false)]
public partial class Order {
    
    private string purchaseOrderIdField;
    
    private string customerOrderIdField;
    
    private string customerEmailIdField;
    
    private System.DateTime orderDateField;
    
    private shippingInfoType shippingInfoField;
    
    private orderLineType[] orderLinesField;
    
    /// <remarks/>
    public string purchaseOrderId {
        get {
            return this.purchaseOrderIdField;
        }
        set {
            this.purchaseOrderIdField = value;
        }
    }
    
    /// <remarks/>
    public string customerOrderId {
        get {
            return this.customerOrderIdField;
        }
        set {
            this.customerOrderIdField = value;
        }
    }
    
    /// <remarks/>
    public string customerEmailId {
        get {
            return this.customerEmailIdField;
        }
        set {
            this.customerEmailIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime orderDate {
        get {
            return this.orderDateField;
        }
        set {
            this.orderDateField = value;
        }
    }
    
    /// <remarks/>
    public shippingInfoType shippingInfo {
        get {
            return this.shippingInfoField;
        }
        set {
            this.shippingInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("orderLine", IsNullable=false)]
    public orderLineType[] orderLines {
        get {
            return this.orderLinesField;
        }
        set {
            this.orderLinesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class shippingInfoType {
    
    private string phoneField;
    
    private System.DateTime estimatedDeliveryDateField;
    
    private shippingMethodCodeType methodCodeField;
    
    private postalAddressType postalAddressField;
    
    /// <remarks/>
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime estimatedDeliveryDate {
        get {
            return this.estimatedDeliveryDateField;
        }
        set {
            this.estimatedDeliveryDateField = value;
        }
    }
    
    /// <remarks/>
    public shippingMethodCodeType methodCode {
        get {
            return this.methodCodeField;
        }
        set {
            this.methodCodeField = value;
        }
    }
    
    /// <remarks/>
    public postalAddressType postalAddress {
        get {
            return this.postalAddressField;
        }
        set {
            this.postalAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public enum shippingMethodCodeType {
    
    /// <remarks/>
    Standard,
    
    /// <remarks/>
    Express,
    
    /// <remarks/>
    OneDay,
    
    /// <remarks/>
    Freight,
    
    /// <remarks/>
    WhiteGlove,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class postalAddressType {
    
    private string nameField;
    
    private string address1Field;
    
    private string address2Field;
    
    private string cityField;
    
    private string stateField;
    
    private string postalCodeField;
    
    private string countryField;
    
    private string addressTypeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    public string address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string addressType {
        get {
            return this.addressTypeField;
        }
        set {
            this.addressTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class metaType {
    
    private int totalCountField;
    
    private int limitField;
    
    private string nextCursorField;
    
    /// <remarks/>
    public int totalCount {
        get {
            return this.totalCountField;
        }
        set {
            this.totalCountField = value;
        }
    }
    
    /// <remarks/>
    public int limit {
        get {
            return this.limitField;
        }
        set {
            this.limitField = value;
        }
    }
    
    /// <remarks/>
    public string nextCursor {
        get {
            return this.nextCursorField;
        }
        set {
            this.nextCursorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class refundType {
    
    private string refundIdField;
    
    private reasonCodesType refundReasonField;
    
    private string refundCommentsField;
    
    private chargeType[] chargesField;
    
    /// <remarks/>
    public string refundId {
        get {
            return this.refundIdField;
        }
        set {
            this.refundIdField = value;
        }
    }
    
    /// <remarks/>
    public reasonCodesType refundReason {
        get {
            return this.refundReasonField;
        }
        set {
            this.refundReasonField = value;
        }
    }
    
    /// <remarks/>
    public string refundComments {
        get {
            return this.refundCommentsField;
        }
        set {
            this.refundCommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("charge", IsNullable=false)]
    public chargeType[] charges {
        get {
            return this.chargesField;
        }
        set {
            this.chargesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public enum reasonCodesType {
    
    /// <remarks/>
    BillingError,
    
    /// <remarks/>
    TaxExemptCustomer,
    
    /// <remarks/>
    ItemNotAsAdvertised,
    
    /// <remarks/>
    IncorrectItemReceived,
    
    /// <remarks/>
    CancelledYetShipped,
    
    /// <remarks/>
    ItemNotReceivedByCustomer,
    
    /// <remarks/>
    IncorrectShippingPrice,
    
    /// <remarks/>
    DamagedItem,
    
    /// <remarks/>
    DefectiveItem,
    
    /// <remarks/>
    CustomerChangedMind,
    
    /// <remarks/>
    CustomerReceivedItemLate,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class chargeType {
    
    private string chargeType1Field;
    
    private string chargeNameField;
    
    private moneyType chargeAmountField;
    
    private taxType taxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chargeType")]
    public string chargeType1 {
        get {
            return this.chargeType1Field;
        }
        set {
            this.chargeType1Field = value;
        }
    }
    
    /// <remarks/>
    public string chargeName {
        get {
            return this.chargeNameField;
        }
        set {
            this.chargeNameField = value;
        }
    }
    
    /// <remarks/>
    public moneyType chargeAmount {
        get {
            return this.chargeAmountField;
        }
        set {
            this.chargeAmountField = value;
        }
    }
    
    /// <remarks/>
    public taxType tax {
        get {
            return this.taxField;
        }
        set {
            this.taxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class moneyType {
    
    private currencyType currencyField;
    
    private decimal amountField;
    
    /// <remarks/>
    public currencyType currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public enum currencyType {
    
    /// <remarks/>
    AED,
    
    /// <remarks/>
    AFN,
    
    /// <remarks/>
    ALL,
    
    /// <remarks/>
    AMD,
    
    /// <remarks/>
    ANG,
    
    /// <remarks/>
    AOA,
    
    /// <remarks/>
    ARS,
    
    /// <remarks/>
    AUD,
    
    /// <remarks/>
    AWG,
    
    /// <remarks/>
    AZN,
    
    /// <remarks/>
    BAM,
    
    /// <remarks/>
    BBD,
    
    /// <remarks/>
    BDT,
    
    /// <remarks/>
    BGN,
    
    /// <remarks/>
    BHD,
    
    /// <remarks/>
    BIF,
    
    /// <remarks/>
    BMD,
    
    /// <remarks/>
    BND,
    
    /// <remarks/>
    BOB,
    
    /// <remarks/>
    BRL,
    
    /// <remarks/>
    BSD,
    
    /// <remarks/>
    BTN,
    
    /// <remarks/>
    BWP,
    
    /// <remarks/>
    BYR,
    
    /// <remarks/>
    BZD,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    CDF,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    CLP,
    
    /// <remarks/>
    CNY,
    
    /// <remarks/>
    COP,
    
    /// <remarks/>
    CRC,
    
    /// <remarks/>
    CUP,
    
    /// <remarks/>
    CVE,
    
    /// <remarks/>
    CZK,
    
    /// <remarks/>
    DJF,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    DOP,
    
    /// <remarks/>
    DZD,
    
    /// <remarks/>
    EGP,
    
    /// <remarks/>
    ERN,
    
    /// <remarks/>
    ETB,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    FJD,
    
    /// <remarks/>
    FKP,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    GEL,
    
    /// <remarks/>
    GHS,
    
    /// <remarks/>
    GIP,
    
    /// <remarks/>
    GMD,
    
    /// <remarks/>
    GNF,
    
    /// <remarks/>
    GTQ,
    
    /// <remarks/>
    GYD,
    
    /// <remarks/>
    HKD,
    
    /// <remarks/>
    HNL,
    
    /// <remarks/>
    HRK,
    
    /// <remarks/>
    HTG,
    
    /// <remarks/>
    HUF,
    
    /// <remarks/>
    IDR,
    
    /// <remarks/>
    ILS,
    
    /// <remarks/>
    INR,
    
    /// <remarks/>
    IQD,
    
    /// <remarks/>
    IRR,
    
    /// <remarks/>
    ISK,
    
    /// <remarks/>
    JMD,
    
    /// <remarks/>
    JOD,
    
    /// <remarks/>
    JPY,
    
    /// <remarks/>
    KES,
    
    /// <remarks/>
    KGS,
    
    /// <remarks/>
    KHR,
    
    /// <remarks/>
    KMF,
    
    /// <remarks/>
    KPW,
    
    /// <remarks/>
    KRW,
    
    /// <remarks/>
    KWD,
    
    /// <remarks/>
    KYD,
    
    /// <remarks/>
    KZT,
    
    /// <remarks/>
    LAK,
    
    /// <remarks/>
    LBP,
    
    /// <remarks/>
    LKR,
    
    /// <remarks/>
    LRD,
    
    /// <remarks/>
    LSL,
    
    /// <remarks/>
    LTL,
    
    /// <remarks/>
    LVL,
    
    /// <remarks/>
    LYD,
    
    /// <remarks/>
    MAD,
    
    /// <remarks/>
    MDL,
    
    /// <remarks/>
    MGA,
    
    /// <remarks/>
    MKD,
    
    /// <remarks/>
    MMK,
    
    /// <remarks/>
    MNT,
    
    /// <remarks/>
    MOP,
    
    /// <remarks/>
    MRO,
    
    /// <remarks/>
    MUR,
    
    /// <remarks/>
    MVR,
    
    /// <remarks/>
    MWK,
    
    /// <remarks/>
    MXN,
    
    /// <remarks/>
    MYR,
    
    /// <remarks/>
    MZN,
    
    /// <remarks/>
    NAD,
    
    /// <remarks/>
    NGN,
    
    /// <remarks/>
    NIO,
    
    /// <remarks/>
    NOK,
    
    /// <remarks/>
    NPR,
    
    /// <remarks/>
    NZD,
    
    /// <remarks/>
    OMR,
    
    /// <remarks/>
    PAB,
    
    /// <remarks/>
    PEN,
    
    /// <remarks/>
    PGK,
    
    /// <remarks/>
    PHP,
    
    /// <remarks/>
    PKR,
    
    /// <remarks/>
    PLN,
    
    /// <remarks/>
    PYG,
    
    /// <remarks/>
    QAR,
    
    /// <remarks/>
    RON,
    
    /// <remarks/>
    RSD,
    
    /// <remarks/>
    RUB,
    
    /// <remarks/>
    RUR,
    
    /// <remarks/>
    RWF,
    
    /// <remarks/>
    SAR,
    
    /// <remarks/>
    SBD,
    
    /// <remarks/>
    SCR,
    
    /// <remarks/>
    SDG,
    
    /// <remarks/>
    SEK,
    
    /// <remarks/>
    SGD,
    
    /// <remarks/>
    SHP,
    
    /// <remarks/>
    SLL,
    
    /// <remarks/>
    SOS,
    
    /// <remarks/>
    SRD,
    
    /// <remarks/>
    STD,
    
    /// <remarks/>
    SYP,
    
    /// <remarks/>
    SZL,
    
    /// <remarks/>
    THB,
    
    /// <remarks/>
    TJS,
    
    /// <remarks/>
    TMT,
    
    /// <remarks/>
    TND,
    
    /// <remarks/>
    TOP,
    
    /// <remarks/>
    TRY,
    
    /// <remarks/>
    TTD,
    
    /// <remarks/>
    TWD,
    
    /// <remarks/>
    TZS,
    
    /// <remarks/>
    UAH,
    
    /// <remarks/>
    UGX,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    UYU,
    
    /// <remarks/>
    UZS,
    
    /// <remarks/>
    VEF,
    
    /// <remarks/>
    VND,
    
    /// <remarks/>
    VUV,
    
    /// <remarks/>
    WST,
    
    /// <remarks/>
    XAF,
    
    /// <remarks/>
    XAG,
    
    /// <remarks/>
    XAU,
    
    /// <remarks/>
    XBA,
    
    /// <remarks/>
    XBB,
    
    /// <remarks/>
    XBC,
    
    /// <remarks/>
    XBD,
    
    /// <remarks/>
    XCD,
    
    /// <remarks/>
    XDR,
    
    /// <remarks/>
    XFU,
    
    /// <remarks/>
    XOF,
    
    /// <remarks/>
    XPD,
    
    /// <remarks/>
    XPF,
    
    /// <remarks/>
    XPT,
    
    /// <remarks/>
    XTS,
    
    /// <remarks/>
    XXX,
    
    /// <remarks/>
    YER,
    
    /// <remarks/>
    ZAR,
    
    /// <remarks/>
    ZMK,
    
    /// <remarks/>
    ZWL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class taxType {
    
    private string taxNameField;
    
    private moneyType taxAmountField;
    
    /// <remarks/>
    public string taxName {
        get {
            return this.taxNameField;
        }
        set {
            this.taxNameField = value;
        }
    }
    
    /// <remarks/>
    public moneyType taxAmount {
        get {
            return this.taxAmountField;
        }
        set {
            this.taxAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class carrierNameType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("carrier", typeof(carrierType))]
    [System.Xml.Serialization.XmlElementAttribute("otherCarrier", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public enum carrierType {
    
    /// <remarks/>
    UPS,
    
    /// <remarks/>
    USPS,
    
    /// <remarks/>
    FedEx,
    
    /// <remarks/>
    Airborne,
    
    /// <remarks/>
    OnTrac,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class trackingInfoType {
    
    private System.DateTime shipDateTimeField;
    
    private carrierNameType carrierNameField;
    
    private shippingMethodCodeType methodCodeField;
    
    private string trackingNumberField;
    
    private string trackingURLField;
    
    /// <remarks/>
    public System.DateTime shipDateTime {
        get {
            return this.shipDateTimeField;
        }
        set {
            this.shipDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public carrierNameType carrierName {
        get {
            return this.carrierNameField;
        }
        set {
            this.carrierNameField = value;
        }
    }
    
    /// <remarks/>
    public shippingMethodCodeType methodCode {
        get {
            return this.methodCodeField;
        }
        set {
            this.methodCodeField = value;
        }
    }
    
    /// <remarks/>
    public string trackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string trackingURL {
        get {
            return this.trackingURLField;
        }
        set {
            this.trackingURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class orderLineStatusType {
    
    private orderLineStatusValueType statusField;
    
    private quantityType statusQuantityField;
    
    private string cancellationReasonField;
    
    private trackingInfoType trackingInfoField;
    
    /// <remarks/>
    public orderLineStatusValueType status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public quantityType statusQuantity {
        get {
            return this.statusQuantityField;
        }
        set {
            this.statusQuantityField = value;
        }
    }
    
    /// <remarks/>
    public string cancellationReason {
        get {
            return this.cancellationReasonField;
        }
        set {
            this.cancellationReasonField = value;
        }
    }
    
    /// <remarks/>
    public trackingInfoType trackingInfo {
        get {
            return this.trackingInfoField;
        }
        set {
            this.trackingInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public enum orderLineStatusValueType {
    
    /// <remarks/>
    Created,
    
    /// <remarks/>
    Acknowledged,
    
    /// <remarks/>
    Shipped,
    
    /// <remarks/>
    Cancelled,
    
    /// <remarks/>
    Refund,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class quantityType {
    
    private string unitOfMeasurementField;
    
    private string amountField;
    
    /// <remarks/>
    public string unitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
    
    /// <remarks/>
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class itemType {
    
    private string productNameField;
    
    private string skuField;
    
    /// <remarks/>
    public string productName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    public string sku {
        get {
            return this.skuField;
        }
        set {
            this.skuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
public partial class orderLineType {
    
    private string lineNumberField;
    
    private itemType itemField;
    
    private chargeType[] chargesField;
    
    private quantityType orderLineQuantityField;
    
    private System.DateTime statusDateField;
    
    private orderLineStatusType[] orderLineStatusesField;
    
    private refundType refundField;
    
    /// <remarks/>
    public string lineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    public itemType item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("charge", IsNullable=false)]
    public chargeType[] charges {
        get {
            return this.chargesField;
        }
        set {
            this.chargesField = value;
        }
    }
    
    /// <remarks/>
    public quantityType orderLineQuantity {
        get {
            return this.orderLineQuantityField;
        }
        set {
            this.orderLineQuantityField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime statusDate {
        get {
            return this.statusDateField;
        }
        set {
            this.statusDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("orderLineStatus", IsNullable=false)]
    public orderLineStatusType[] orderLineStatuses {
        get {
            return this.orderLineStatusesField;
        }
        set {
            this.orderLineStatusesField = value;
        }
    }
    
    /// <remarks/>
    public refundType refund {
        get {
            return this.refundField;
        }
        set {
            this.refundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
[System.Xml.Serialization.XmlRootAttribute("list", Namespace="http://walmart.com/mp/orders", IsNullable=false)]
public partial class ordersListType {
    
    private metaType metaField;
    
    private Order[] elementsField;
    
    /// <remarks/>
    public metaType meta {
        get {
            return this.metaField;
        }
        set {
            this.metaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("order")]
    public Order[] elements {
        get {
            return this.elementsField;
        }
        set {
            this.elementsField = value;
        }
    }
}
